<a href="https://colab.research.google.com/github/jhajagos/SupportingConceptSetGeneration/blob/main/umls_load_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Install libraries

In [ ]:
import sqlalchemy as sa
import sqlparse
import pandas as pd
import pyspark

### Load UMLS DDL into in memory SQLite database

In [ ]:
umls_ddl_script = """

DROP TABLE MRCOC;
CREATE TABLE MRCOC (
	CUI1	char(8) NOT NULL,
	AUI1	varchar(9) NOT NULL,
	CUI2	char(8),
	AUI2	varchar(9),
	SAB	varchar(20) NOT NULL,
	COT	varchar(3) NOT NULL,
	COF	int,
	COA	text,
	CVF	int,
	dummy char(1)
);
copy MRCOC from 'META/MRCOC.RRF' with delimiter as '|' null as '';
alter table mrcoc drop column dummy;

DROP TABLE MRCOLS;
CREATE TABLE MRCOLS (
	COL	varchar(20),
	DES	varchar(200),
	REF	varchar(20),
	MIN	int,
	AV	numeric(5,2),
	MAX	int,
	FIL	varchar(50),
	DTY	varchar(20),
	dummy char(1)
);
copy MRCOLS from 'META/MRCOLS.RRF' with delimiter as '|' null as '';
alter table mrcols drop column dummy;

DROP TABLE MRCONSO;
CREATE TABLE MRCONSO (
	CUI	char(8) NOT NULL,
	LAT	char(3) NOT NULL,
	TS	char(1) NOT NULL,
	LUI	char(8) NOT NULL,
	STT	varchar(3) NOT NULL,
	SUI	char(8) NOT NULL,
	ISPREF	char(1) NOT NULL,
	AUI	varchar(9) NOT NULL,
	SAUI	varchar(50),
	SCUI	varchar(50),
	SDUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	TTY	varchar(20) NOT NULL,
	CODE	varchar(50) NOT NULL,
	STR	text NOT NULL,
	SRL	int NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
copy MRCONSO from 'META/MRCONSO.RRF' with delimiter as '|' null as '';
alter table mrconso drop column dummy;

DROP TABLE MRCUI;
CREATE TABLE MRCUI (
	CUI1	char(8) NOT NULL,
	VER	varchar(10) NOT NULL,
	REL	varchar(4) NOT NULL,
	RELA	varchar(100),
	MAPREASON	text,
	CUI2	char(8),
	MAPIN	char(1),
	dummy char(1)
);
copy MRCUI from 'META/MRCUI.RRF' with delimiter as '|' null as '';
alter table mrcui drop column dummy;

DROP TABLE MRCXT;
CREATE TABLE MRCXT (
	CUI	char(8),
	SUI	char(8),
	AUI	varchar(9),
	SAB	varchar(20),
	CODE	varchar(50),
	CXN	int,
	CXL	char(3),
	RANK	int,
	CXS	text,
	CUI2	char(8),
	AUI2	varchar(9),
	HCD	varchar(50),
	RELA	varchar(100),
	XC	varchar(1),
	CVF	int,
	dummy char(1)
);
copy MRCXT from 'META/MRCXT.RRF' with delimiter as '|' null as '';
alter table mrcxt drop column dummy;

DROP TABLE MRDEF;
CREATE TABLE MRDEF (
	CUI	char(8) NOT NULL,
	AUI	varchar(9) NOT NULL,
	ATUI	varchar(10) NOT NULL,
	SATUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	DEF	text NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
copy MRDEF from 'META/MRDEF.RRF' with delimiter as '|' null as '';
alter table mrdef drop column dummy;

DROP TABLE MRDOC;
CREATE TABLE MRDOC (
	DOCKEY	varchar(50) NOT NULL,
	VALUE	varchar(200),
	TYPE	varchar(50) NOT NULL,
	EXPL	text,
	dummy char(1)
);
copy MRDOC from 'META/MRDOC.RRF' with delimiter as '|' null as '';
alter table mrdoc drop column dummy;

DROP TABLE MRFILES;
CREATE TABLE MRFILES (
	FIL	varchar(50),
	DES	varchar(200),
	FMT	text,
	CLS	int,
	RWS	int,
	BTS	bigint,
	dummy char(1)
);
copy MRFILES from 'META/MRFILES.RRF' with delimiter as '|' null as '';
alter table mrfiles drop column dummy;

DROP TABLE MRHIER;
CREATE TABLE MRHIER (
	CUI	char(8) NOT NULL,
	AUI	varchar(9) NOT NULL,
	CXN	int NOT NULL,
	PAUI	varchar(9),
	SAB	varchar(20) NOT NULL,
	RELA	varchar(100),
	PTR	text,
	HCD	varchar(50),
	CVF	int,
	dummy char(1)
);
copy MRHIER from 'META/MRHIER.RRF' with delimiter as '|' null as '';
alter table mrhier drop column dummy;

DROP TABLE MRHIST;
CREATE TABLE MRHIST (
	CUI	char(8) NOT NULL,
	SOURCEUI	varchar(50) NOT NULL,
	SAB	varchar(20) NOT NULL,
	SVER	varchar(20) NOT NULL,
	CHANGETYPE	text NOT NULL,
	CHANGEKEY	text NOT NULL,
	CHANGEVAL	text NOT NULL,
	REASON	text,
	CVF	int,
	dummy char(1)
);
copy MRHIST from 'META/MRHIST.RRF' with delimiter as '|' null as '';
alter table mrhist drop column dummy;

DROP TABLE MRMAP;
CREATE TABLE MRMAP (
	MAPSETCUI	char(8),
	MAPSETSAB	varchar(20),
	MAPSUBSETID	varchar(10),
	MAPRANK	int,
	MAPID	varchar(50),
	MAPSID	varchar(50),
	FROMID	varchar(50),
	FROMSID	varchar(50),
	FROMEXPR	text,
	FROMTYPE	varchar(50),
	FROMRULE	text,
	FROMRES	text,
	REL	varchar(4),
	RELA	varchar(100),
	TOID	varchar(50),
	TOSID	varchar(50),
	TOEXPR	text,
	TOTYPE	varchar(50),
	TORULE	text,
	TORES	text,
	MAPRULE	text,
	MAPRES	text,
	MAPTYPE	varchar(50),
	MAPATN	varchar(20),
	MAPATV	text,
	CVF	int,
	dummy char(1)
);
copy MRMAP from 'META/MRMAP.RRF' with delimiter as '|' null as '';
alter table mrmap drop column dummy;

DROP TABLE MRRANK;
CREATE TABLE MRRANK (
	RANK	int NOT NULL,
	SAB	varchar(20) NOT NULL,
	TTY	varchar(20) NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	dummy char(1)
);
copy MRRANK from 'META/MRRANK.RRF' with delimiter as '|' null as '';
alter table mrrank drop column dummy;

DROP TABLE MRREL;
CREATE TABLE MRREL (
	CUI1	char(8) NOT NULL,
	AUI1	varchar(9),
	STYPE1	varchar(50) NOT NULL,
	REL	varchar(4) NOT NULL,
	CUI2	char(8) NOT NULL,
	AUI2	varchar(9),
	STYPE2	varchar(50) NOT NULL,
	RELA	varchar(100),
	RUI	varchar(10) NOT NULL,
	SRUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	SL	varchar(20) NOT NULL,
	RG	varchar(10),
	DIR	varchar(1),
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
copy MRREL from 'META/MRREL.RRF' with delimiter as '|' null as '';
alter table mrrel drop column dummy;

DROP TABLE MRSAB;
CREATE TABLE MRSAB (
	VCUI	char(8),
	RCUI	char(8) NOT NULL,
	VSAB	varchar(20) NOT NULL,
	RSAB	varchar(20) NOT NULL,
	SON	text NOT NULL,
	SF	varchar(20) NOT NULL,
	SVER	varchar(20),
	VSTART	char(10),
	VEND	char(10),
	IMETA	varchar(10) NOT NULL,
	RMETA	varchar(10),
	SLC	text,
	SCC	text,
	SRL	int NOT NULL,
	TFR	int,
	CFR	int,
	CXTY	varchar(50),
	TTYL	varchar(200),
	ATNL	text,
	LAT	char(3),
	CENC	varchar(20) NOT NULL,
	CURVER	char(1) NOT NULL,
	SABIN	char(1) NOT NULL,
	SSN	text NOT NULL,
	SCIT	text NOT NULL,
	dummy char(1)
);
copy MRSAB from 'META/MRSAB.RRF' with delimiter as '|' null as '';
alter table mrsab drop column dummy;

DROP TABLE MRSAT;
CREATE TABLE MRSAT (
	CUI	char(8) NOT NULL,
	LUI	char(8),
	SUI	char(8),
	METAUI	varchar(50),
	STYPE	varchar(50) NOT NULL,
	CODE	varchar(50),
	ATUI	varchar(10) NOT NULL,
	SATUI	varchar(50),
	ATN	varchar(50) NOT NULL,
	SAB	varchar(20) NOT NULL,
	ATV	text,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
copy MRSAT from 'META/MRSAT.RRF' with delimiter as '|' null as '';
alter table mrsat drop column dummy;

DROP TABLE MRSMAP;
CREATE TABLE MRSMAP (
	MAPSETCUI	char(8),
	MAPSETSAB	varchar(20),
	MAPID	varchar(50),
	MAPSID	varchar(50),
	FROMEXPR	text,
	FROMTYPE	varchar(50),
	REL	varchar(4),
	RELA	varchar(100),
	TOEXPR	text,
	TOTYPE	varchar(50),
	CVF	int,
	dummy char(1)
);
copy MRSMAP from 'META/MRSMAP.RRF' with delimiter as '|' null as '';
alter table mrsmap drop column dummy;

DROP TABLE MRSTY;
CREATE TABLE MRSTY (
	CUI	char(8) NOT NULL,
	TUI	char(4) NOT NULL,
	STN	varchar(100) NOT NULL,
	STY	varchar(50) NOT NULL,
	ATUI	varchar(10) NOT NULL,
	CVF	int,
	dummy char(1)
);
copy MRSTY from 'META/MRSTY.RRF' with delimiter as '|' null as '';
alter table mrsty drop column dummy;

DROP TABLE MRXNS_ENG;
CREATE TABLE MRXNS_ENG (
	LAT	char(3) NOT NULL,
	NSTR	text NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXNS_ENG from 'META/MRXNS_ENG.RRF' with delimiter as '|' null as '';
alter table mrxns_eng drop column dummy;

DROP TABLE MRXNW_ENG;
CREATE TABLE MRXNW_ENG (
	LAT	char(3) NOT NULL,
	NWD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXNW_ENG from 'META/MRXNW_ENG.RRF' with delimiter as '|' null as '';
alter table mrxnw_eng drop column dummy;

DROP TABLE MRAUI;
CREATE TABLE MRAUI (
	AUI1	varchar(9) NOT NULL,
	CUI1	char(8) NOT NULL,
	VER	varchar(10) NOT NULL,
	REL	varchar(4),
	RELA	varchar(100),
	MAPREASON	text NOT NULL,
	AUI2	varchar(9) NOT NULL,
	CUI2	char(8) NOT NULL,
	MAPIN	char(1) NOT NULL,
	dummy char(1)
);
copy MRAUI from 'META/MRAUI.RRF' with delimiter as '|' null as '';
alter table mraui drop column dummy;

DROP TABLE MRXW_BAQ;
CREATE TABLE MRXW_BAQ (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_BAQ from 'META/MRXW_BAQ.RRF' with delimiter as '|' null as '';
alter table mrxw_baq drop column dummy;

DROP TABLE MRXW_CZE;
CREATE TABLE MRXW_CZE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_CZE from 'META/MRXW_CZE.RRF' with delimiter as '|' null as '';
alter table mrxw_cze drop column dummy;

DROP TABLE MRXW_DAN;
CREATE TABLE MRXW_DAN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_DAN from 'META/MRXW_DAN.RRF' with delimiter as '|' null as '';
alter table mrxw_dan drop column dummy;

DROP TABLE MRXW_DUT;
CREATE TABLE MRXW_DUT (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_DUT from 'META/MRXW_DUT.RRF' with delimiter as '|' null as '';
alter table mrxw_dut drop column dummy;

DROP TABLE MRXW_ENG;
CREATE TABLE MRXW_ENG (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_ENG from 'META/MRXW_ENG.RRF' with delimiter as '|' null as '';
alter table mrxw_eng drop column dummy;

DROP TABLE MRXW_FIN;
CREATE TABLE MRXW_FIN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_FIN from 'META/MRXW_FIN.RRF' with delimiter as '|' null as '';
alter table mrxw_fin drop column dummy;

DROP TABLE MRXW_FRE;
CREATE TABLE MRXW_FRE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_FRE from 'META/MRXW_FRE.RRF' with delimiter as '|' null as '';
alter table mrxw_fre drop column dummy;

DROP TABLE MRXW_GER;
CREATE TABLE MRXW_GER (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_GER from 'META/MRXW_GER.RRF' with delimiter as '|' null as '';
alter table mrxw_ger drop column dummy;

DROP TABLE MRXW_HEB;
CREATE TABLE MRXW_HEB (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_HEB from 'META/MRXW_HEB.RRF' with delimiter as '|' null as '';
alter table mrxw_heb drop column dummy;

DROP TABLE MRXW_HUN;
CREATE TABLE MRXW_HUN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_HUN from 'META/MRXW_HUN.RRF' with delimiter as '|' null as '';
alter table mrxw_hun drop column dummy;

DROP TABLE MRXW_ITA;
CREATE TABLE MRXW_ITA (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_ITA from 'META/MRXW_ITA.RRF' with delimiter as '|' null as '';
alter table mrxw_ita drop column dummy;

DROP TABLE MRXW_JPN;
CREATE TABLE MRXW_JPN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_JPN from 'META/MRXW_JPN.RRF' with delimiter as '|' null as '';
alter table mrxw_jpn drop column dummy;

DROP TABLE MRXW_NOR;
CREATE TABLE MRXW_NOR (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_NOR from 'META/MRXW_NOR.RRF' with delimiter as '|' null as '';
alter table mrxw_nor drop column dummy;

DROP TABLE MRXW_POR;
CREATE TABLE MRXW_POR (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_POR from 'META/MRXW_POR.RRF' with delimiter as '|' null as '';
alter table mrxw_por drop column dummy;

DROP TABLE MRXW_RUS;
CREATE TABLE MRXW_RUS (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_RUS from 'META/MRXW_RUS.RRF' with delimiter as '|' null as '';
alter table mrxw_rus drop column dummy;

DROP TABLE MRXW_SPA;
CREATE TABLE MRXW_SPA (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_SPA from 'META/MRXW_SPA.RRF' with delimiter as '|' null as '';
alter table mrxw_spa drop column dummy;

DROP TABLE MRXW_SWE;
CREATE TABLE MRXW_SWE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
copy MRXW_SWE from 'META/MRXW_SWE.RRF' with delimiter as '|' null as '';
alter table mrxw_swe drop column dummy;

DROP TABLE AMBIGSUI;
CREATE TABLE AMBIGSUI (
	SUI	char(8) NOT NULL,
	CUI	char(8) NOT NULL,
	dummy char(1)
);
copy AMBIGSUI from 'META/AMBIGSUI.RRF' with delimiter as '|' null as '';
alter table ambigsui drop column dummy;

DROP TABLE AMBIGLUI;
CREATE TABLE AMBIGLUI (
	LUI	char(8) NOT NULL,
	CUI	char(8) NOT NULL,
	dummy char(1)
);
copy AMBIGLUI from 'META/AMBIGLUI.RRF' with delimiter as '|' null as '';
alter table ambiglui drop column dummy;

DROP TABLE DELETEDCUI;
CREATE TABLE DELETEDCUI (
	PCUI	char(8) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
copy DELETEDCUI from 'META/DELETEDCUI.RRF' with delimiter as '|' null as '';
alter table deletedcui drop column dummy;

DROP TABLE DELETEDLUI;
CREATE TABLE DELETEDLUI (
	PLUI	char(8) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
copy DELETEDLUI from 'META/DELETEDLUI.RRF' with delimiter as '|' null as '';
alter table deletedlui drop column dummy;

DROP TABLE DELETEDSUI;
CREATE TABLE DELETEDSUI (
	PSUI	char(8) NOT NULL,
	LAT	char(3) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
copy DELETEDSUI from 'META/DELETEDSUI.RRF' with delimiter as '|' null as '';
alter table deletedsui drop column dummy;

DROP TABLE MERGEDCUI;
CREATE TABLE MERGEDCUI (
	PCUI	char(8) NOT NULL,
	CUI	char(8) NOT NULL,
	dummy char(1)
);
copy MERGEDCUI from 'META/MERGEDCUI.RRF' with delimiter as '|' null as '';
alter table mergedcui drop column dummy;

DROP TABLE MERGEDLUI;
CREATE TABLE MERGEDLUI (
	PLUI	char(8),
	LUI	char(8),
	dummy char(1)
);
copy MERGEDLUI from 'META/MERGEDLUI.RRF' with delimiter as '|' null as '';
alter table mergedlui drop column dummy;


"""

In [ ]:
engine = sa.create_engine("sqlite:///:memory")

In [ ]:
umls_ddl_statements_filtered = [s for s in sqlparse.split(umls_ddl_script) if "CREATE TABLE" in s or "DROP TABLE" in s] # We only want to run create table statements

In [ ]:
connection = engine.connect()
with connection.begin():
  for statement in umls_ddl_statements_filtered:
    print(statement)
    try:
      connection.execute(sa.text(statement))
    except:
      pass

DROP TABLE MRCOC;
CREATE TABLE MRCOC (
	CUI1	char(8) NOT NULL,
	AUI1	varchar(9) NOT NULL,
	CUI2	char(8),
	AUI2	varchar(9),
	SAB	varchar(20) NOT NULL,
	COT	varchar(3) NOT NULL,
	COF	int,
	COA	text,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRCOLS;
CREATE TABLE MRCOLS (
	COL	varchar(20),
	DES	varchar(200),
	REF	varchar(20),
	MIN	int,
	AV	numeric(5,2),
	MAX	int,
	FIL	varchar(50),
	DTY	varchar(20),
	dummy char(1)
);
DROP TABLE MRCONSO;
CREATE TABLE MRCONSO (
	CUI	char(8) NOT NULL,
	LAT	char(3) NOT NULL,
	TS	char(1) NOT NULL,
	LUI	char(8) NOT NULL,
	STT	varchar(3) NOT NULL,
	SUI	char(8) NOT NULL,
	ISPREF	char(1) NOT NULL,
	AUI	varchar(9) NOT NULL,
	SAUI	varchar(50),
	SCUI	varchar(50),
	SDUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	TTY	varchar(20) NOT NULL,
	CODE	varchar(50) NOT NULL,
	STR	text NOT NULL,
	SRL	int NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRCUI;
CREATE TABLE MRCUI (
	CUI1	char(8) NOT NULL,
	VER	varchar(10) NOT NULL,
	REL	varchar(4) NOT NULL,
	RELA	varchar(100),
	MAPREASON	text,
	CUI2	char(8),
	MAPIN	char(1),
	dummy char(1)
);
DROP TABLE MRCXT;
CREATE TABLE MRCXT (
	CUI	char(8),
	SUI	char(8),
	AUI	varchar(9),
	SAB	varchar(20),
	CODE	varchar(50),
	CXN	int,
	CXL	char(3),
	RANK	int,
	CXS	text,
	CUI2	char(8),
	AUI2	varchar(9),
	HCD	varchar(50),
	RELA	varchar(100),
	XC	varchar(1),
	CVF	int,
	dummy char(1)
);
DROP TABLE MRDEF;
CREATE TABLE MRDEF (
	CUI	char(8) NOT NULL,
	AUI	varchar(9) NOT NULL,
	ATUI	varchar(10) NOT NULL,
	SATUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	DEF	text NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRDOC;
CREATE TABLE MRDOC (
	DOCKEY	varchar(50) NOT NULL,
	VALUE	varchar(200),
	TYPE	varchar(50) NOT NULL,
	EXPL	text,
	dummy char(1)
);
DROP TABLE MRFILES;
CREATE TABLE MRFILES (
	FIL	varchar(50),
	DES	varchar(200),
	FMT	text,
	CLS	int,
	RWS	int,
	BTS	bigint,
	dummy char(1)
);
DROP TABLE MRHIER;
CREATE TABLE MRHIER (
	CUI	char(8) NOT NULL,
	AUI	varchar(9) NOT NULL,
	CXN	int NOT NULL,
	PAUI	varchar(9),
	SAB	varchar(20) NOT NULL,
	RELA	varchar(100),
	PTR	text,
	HCD	varchar(50),
	CVF	int,
	dummy char(1)
);
DROP TABLE MRHIST;
CREATE TABLE MRHIST (
	CUI	char(8) NOT NULL,
	SOURCEUI	varchar(50) NOT NULL,
	SAB	varchar(20) NOT NULL,
	SVER	varchar(20) NOT NULL,
	CHANGETYPE	text NOT NULL,
	CHANGEKEY	text NOT NULL,
	CHANGEVAL	text NOT NULL,
	REASON	text,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRMAP;
CREATE TABLE MRMAP (
	MAPSETCUI	char(8),
	MAPSETSAB	varchar(20),
	MAPSUBSETID	varchar(10),
	MAPRANK	int,
	MAPID	varchar(50),
	MAPSID	varchar(50),
	FROMID	varchar(50),
	FROMSID	varchar(50),
	FROMEXPR	text,
	FROMTYPE	varchar(50),
	FROMRULE	text,
	FROMRES	text,
	REL	varchar(4),
	RELA	varchar(100),
	TOID	varchar(50),
	TOSID	varchar(50),
	TOEXPR	text,
	TOTYPE	varchar(50),
	TORULE	text,
	TORES	text,
	MAPRULE	text,
	MAPRES	text,
	MAPTYPE	varchar(50),
	MAPATN	varchar(20),
	MAPATV	text,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRRANK;
CREATE TABLE MRRANK (
	RANK	int NOT NULL,
	SAB	varchar(20) NOT NULL,
	TTY	varchar(20) NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	dummy char(1)
);
DROP TABLE MRREL;
CREATE TABLE MRREL (
	CUI1	char(8) NOT NULL,
	AUI1	varchar(9),
	STYPE1	varchar(50) NOT NULL,
	REL	varchar(4) NOT NULL,
	CUI2	char(8) NOT NULL,
	AUI2	varchar(9),
	STYPE2	varchar(50) NOT NULL,
	RELA	varchar(100),
	RUI	varchar(10) NOT NULL,
	SRUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	SL	varchar(20) NOT NULL,
	RG	varchar(10),
	DIR	varchar(1),
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRSAB;
CREATE TABLE MRSAB (
	VCUI	char(8),
	RCUI	char(8) NOT NULL,
	VSAB	varchar(20) NOT NULL,
	RSAB	varchar(20) NOT NULL,
	SON	text NOT NULL,
	SF	varchar(20) NOT NULL,
	SVER	varchar(20),
	VSTART	char(10),
	VEND	char(10),
	IMETA	varchar(10) NOT NULL,
	RMETA	varchar(10),
	SLC	text,
	SCC	text,
	SRL	int NOT NULL,
	TFR	int,
	CFR	int,
	CXTY	varchar(50),
	TTYL	varchar(200),
	ATNL	text,
	LAT	char(3),
	CENC	varchar(20) NOT NULL,
	CURVER	char(1) NOT NULL,
	SABIN	char(1) NOT NULL,
	SSN	text NOT NULL,
	SCIT	text NOT NULL,
	dummy char(1)
);
DROP TABLE MRSAT;
CREATE TABLE MRSAT (
	CUI	char(8) NOT NULL,
	LUI	char(8),
	SUI	char(8),
	METAUI	varchar(50),
	STYPE	varchar(50) NOT NULL,
	CODE	varchar(50),
	ATUI	varchar(10) NOT NULL,
	SATUI	varchar(50),
	ATN	varchar(50) NOT NULL,
	SAB	varchar(20) NOT NULL,
	ATV	text,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRSMAP;
CREATE TABLE MRSMAP (
	MAPSETCUI	char(8),
	MAPSETSAB	varchar(20),
	MAPID	varchar(50),
	MAPSID	varchar(50),
	FROMEXPR	text,
	FROMTYPE	varchar(50),
	REL	varchar(4),
	RELA	varchar(100),
	TOEXPR	text,
	TOTYPE	varchar(50),
	CVF	int,
	dummy char(1)
);
DROP TABLE MRSTY;
CREATE TABLE MRSTY (
	CUI	char(8) NOT NULL,
	TUI	char(4) NOT NULL,
	STN	varchar(100) NOT NULL,
	STY	varchar(50) NOT NULL,
	ATUI	varchar(10) NOT NULL,
	CVF	int,
	dummy char(1)
);
DROP TABLE MRXNS_ENG;
CREATE TABLE MRXNS_ENG (
	LAT	char(3) NOT NULL,
	NSTR	text NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXNW_ENG;
CREATE TABLE MRXNW_ENG (
	LAT	char(3) NOT NULL,
	NWD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRAUI;
CREATE TABLE MRAUI (
	AUI1	varchar(9) NOT NULL,
	CUI1	char(8) NOT NULL,
	VER	varchar(10) NOT NULL,
	REL	varchar(4),
	RELA	varchar(100),
	MAPREASON	text NOT NULL,
	AUI2	varchar(9) NOT NULL,
	CUI2	char(8) NOT NULL,
	MAPIN	char(1) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_BAQ;
CREATE TABLE MRXW_BAQ (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_CZE;
CREATE TABLE MRXW_CZE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_DAN;
CREATE TABLE MRXW_DAN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_DUT;
CREATE TABLE MRXW_DUT (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_ENG;
CREATE TABLE MRXW_ENG (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_FIN;
CREATE TABLE MRXW_FIN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_FRE;
CREATE TABLE MRXW_FRE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_GER;
CREATE TABLE MRXW_GER (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_HEB;
CREATE TABLE MRXW_HEB (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_HUN;
CREATE TABLE MRXW_HUN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_ITA;
CREATE TABLE MRXW_ITA (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_JPN;
CREATE TABLE MRXW_JPN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_NOR;
CREATE TABLE MRXW_NOR (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_POR;
CREATE TABLE MRXW_POR (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_RUS;
CREATE TABLE MRXW_RUS (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_SPA;
CREATE TABLE MRXW_SPA (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MRXW_SWE;
CREATE TABLE MRXW_SWE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(8) NOT NULL,
	LUI	char(8) NOT NULL,
	SUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE AMBIGSUI;
CREATE TABLE AMBIGSUI (
	SUI	char(8) NOT NULL,
	CUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE AMBIGLUI;
CREATE TABLE AMBIGLUI (
	LUI	char(8) NOT NULL,
	CUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE DELETEDCUI;
CREATE TABLE DELETEDCUI (
	PCUI	char(8) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
DROP TABLE DELETEDLUI;
CREATE TABLE DELETEDLUI (
	PLUI	char(8) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
DROP TABLE DELETEDSUI;
CREATE TABLE DELETEDSUI (
	PSUI	char(8) NOT NULL,
	LAT	char(3) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
DROP TABLE MERGEDCUI;
CREATE TABLE MERGEDCUI (
	PCUI	char(8) NOT NULL,
	CUI	char(8) NOT NULL,
	dummy char(1)
);
DROP TABLE MERGEDLUI;
CREATE TABLE MERGEDLUI (
	PLUI	char(8),
	LUI	char(8),
	dummy char(1)
);

In [ ]:
import sqlalchemy as sa
import sqlparse
from sqlite3 import OperationalError

In [ ]:
meta_data = sa.MetaData()
meta_data.reflect(bind=connection)

In [ ]:
table_names = [t for t in meta_data.tables]
table_names

['AMBIGLUI',
 'AMBIGSUI',
 'DELETEDCUI',
 'DELETEDLUI',
 'DELETEDSUI',
 'MERGEDCUI',
 'MERGEDLUI',
 'MRAUI',
 'MRCOC',
 'MRCOLS',
 'MRCONSO',
 'MRCUI',
 'MRCXT',
 'MRDEF',
 'MRDOC',
 'MRFILES',
 'MRHIER',
 'MRHIST',
 'MRMAP',
 'MRRANK',
 'MRREL',
 'MRSAB',
 'MRSAT',
 'MRSMAP',
 'MRSTY',
 'MRXNS_ENG',
 'MRXNW_ENG',
 'MRXW_BAQ',
 'MRXW_CZE',
 'MRXW_DAN',
 'MRXW_DUT',
 'MRXW_ENG',
 'MRXW_FIN',
 'MRXW_FRE',
 'MRXW_GER',
 'MRXW_HEB',
 'MRXW_HUN',
 'MRXW_ITA',
 'MRXW_JPN',
 'MRXW_NOR',
 'MRXW_POR',
 'MRXW_RUS',
 'MRXW_SPA',
 'MRXW_SWE']

In [ ]:
table_obj_column_dict = {t: meta_data.tables[t].columns for t in meta_data.tables}
table_column_dict = {}
for table in table_obj_column_dict:
  column_list = []
  for column in table_obj_column_dict[table]:
    column_name = column.name
    column_list += [column_name]
  table_column_dict[table] = column_list
table_column_dict

{'AMBIGLUI': ['LUI', 'CUI', 'dummy'],
 'AMBIGSUI': ['SUI', 'CUI', 'dummy'],
 'DELETEDCUI': ['PCUI', 'PSTR', 'dummy'],
 'DELETEDLUI': ['PLUI', 'PSTR', 'dummy'],
 'DELETEDSUI': ['PSUI', 'LAT', 'PSTR', 'dummy'],
 'MERGEDCUI': ['PCUI', 'CUI', 'dummy'],
 'MERGEDLUI': ['PLUI', 'LUI', 'dummy'],
 'MRAUI': ['AUI1',
  'CUI1',
  'VER',
  'REL',
  'RELA',
  'MAPREASON',
  'AUI2',
  'CUI2',
  'MAPIN',
  'dummy'],
 'MRCOC': ['CUI1',
  'AUI1',
  'CUI2',
  'AUI2',
  'SAB',
  'COT',
  'COF',
  'COA',
  'CVF',
  'dummy'],
 'MRCOLS': ['COL', 'DES', 'REF', 'MIN', 'AV', 'MAX', 'FIL', 'DTY', 'dummy'],
 'MRCONSO': ['CUI',
  'LAT',
  'TS',
  'LUI',
  'STT',
  'SUI',
  'ISPREF',
  'AUI',
  'SAUI',
  'SCUI',
  'SDUI',
  'SAB',
  'TTY',
  'CODE',
  'STR',
  'SRL',
  'SUPPRESS',
  'CVF',
  'dummy'],
 'MRCUI': ['CUI1',
  'VER',
  'REL',
  'RELA',
  'MAPREASON',
  'CUI2',
  'MAPIN',
  'dummy'],
 'MRCXT': ['CUI',
  'SUI',
  'AUI',
  'SAB',
  'CODE',
  'CXN',
  'CXL',
  'RANK',
  'CXS',
  'CUI2',
  'AUI2',
  'HCD',
  'RELA',
  'XC',
  'CVF',
  'dummy'],
 'MRDEF': ['CUI',
  'AUI',
  'ATUI',
  'SATUI',
  'SAB',
  'DEF',
  'SUPPRESS',
  'CVF',
  'dummy'],
 'MRDOC': ['DOCKEY', 'VALUE', 'TYPE', 'EXPL', 'dummy'],
 'MRFILES': ['FIL', 'DES', 'FMT', 'CLS', 'RWS', 'BTS', 'dummy'],
 'MRHIER': ['CUI',
  'AUI',
  'CXN',
  'PAUI',
  'SAB',
  'RELA',
  'PTR',
  'HCD',
  'CVF',
  'dummy'],
 'MRHIST': ['CUI',
  'SOURCEUI',
  'SAB',
  'SVER',
  'CHANGETYPE',
  'CHANGEKEY',
  'CHANGEVAL',
  'REASON',
  'CVF',
  'dummy'],
 'MRMAP': ['MAPSETCUI',
  'MAPSETSAB',
  'MAPSUBSETID',
  'MAPRANK',
  'MAPID',
  'MAPSID',
  'FROMID',
  'FROMSID',
  'FROMEXPR',
  'FROMTYPE',
  'FROMRULE',
  'FROMRES',
  'REL',
  'RELA',
  'TOID',
  'TOSID',
  'TOEXPR',
  'TOTYPE',
  'TORULE',
  'TORES',
  'MAPRULE',
  'MAPRES',
  'MAPTYPE',
  'MAPATN',
  'MAPATV',
  'CVF',
  'dummy'],
 'MRRANK': ['RANK', 'SAB', 'TTY', 'SUPPRESS', 'dummy'],
 'MRREL': ['CUI1',
  'AUI1',
  'STYPE1',
  'REL',
  'CUI2',
  'AUI2',
  'STYPE2',
  'RELA',
  'RUI',
  'SRUI',
  'SAB',
  'SL',
  'RG',
  'DIR',
  'SUPPRESS',
  'CVF',
  'dummy'],
 'MRSAB': ['VCUI',
  'RCUI',
  'VSAB',
  'RSAB',
  'SON',
  'SF',
  'SVER',
  'VSTART',
  'VEND',
  'IMETA',
  'RMETA',
  'SLC',
  'SCC',
  'SRL',
  'TFR',
  'CFR',
  'CXTY',
  'TTYL',
  'ATNL',
  'LAT',
  'CENC',
  'CURVER',
  'SABIN',
  'SSN',
  'SCIT',
  'dummy'],
 'MRSAT': ['CUI',
  'LUI',
  'SUI',
  'METAUI',
  'STYPE',
  'CODE',
  'ATUI',
  'SATUI',
  'ATN',
  'SAB',
  'ATV',
  'SUPPRESS',
  'CVF',
  'dummy'],
 'MRSMAP': ['MAPSETCUI',
  'MAPSETSAB',
  'MAPID',
  'MAPSID',
  'FROMEXPR',
  'FROMTYPE',
  'REL',
  'RELA',
  'TOEXPR',
  'TOTYPE',
  'CVF',
  'dummy'],
 'MRSTY': ['CUI', 'TUI', 'STN', 'STY', 'ATUI', 'CVF', 'dummy'],
 'MRXNS_ENG': ['LAT', 'NSTR', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXNW_ENG': ['LAT', 'NWD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_BAQ': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_CZE': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_DAN': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_DUT': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_ENG': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_FIN': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_FRE': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_GER': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_HEB': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_HUN': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_ITA': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_JPN': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_NOR': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_POR': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_RUS': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_SPA': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy'],
 'MRXW_SWE': ['LAT', 'WD', 'CUI', 'LUI', 'SUI', 'dummy']}

### Load UMLS RRF into Spark Dataframes

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
UMLS_DIRECTORY = "/content/drive/MyDrive/umls/2025AA/"
UMLS_OUTPUT_DIRECTORY = "/content/drive/MyDrive/umls/2025AA/export/"

In [ ]:
import pyspark
spark = pyspark.sql.SparkSession.builder\
    .config("spark.driver.memory", "16g") \
    .getOrCreate()

In [ ]:
import logging
def write_parquet_file_and_reload(spark_ptr, sdf, table_name, output_location):
    """Write Spark Dataframe to a Parquet and then reload it"""

    parquet_path = output_location + table_name + ".parquet"
    sdf.write.mode("overwrite").parquet(parquet_path)

    logging.info(f"Writing '{parquet_path}'")

    sdf = spark_ptr.read.parquet(parquet_path)

    logging.info(f"Reading '{parquet_path}'")

    return sdf, parquet_path

def load_umls_table(table_name, base_path, table_column_dict):
  umls_sdf = spark.read.option("inferSchema", "true").option("header", "false").option("delimiter", "|").csv(base_path + table_name + ".RRF.bz2")
  new_columns = table_column_dict[table_name]
  umls_sdf = umls_sdf.toDF(*new_columns)
  umls_sdf.createOrReplaceTempView(table_name)
  return umls_sdf

In [ ]:
mrconso_sdf = load_umls_table("MRCONSO", UMLS_DIRECTORY, table_column_dict)
mrconso_sdf, mrconso_path = write_parquet_file_and_reload(spark, mrconso_sdf, "MRCONSO", UMLS_OUTPUT_DIRECTORY )

In [ ]:
mrconso_sdf.limit(5).toPandas()

,CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,SDUI,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF,dummy
0,C2104213,ENG,S,L7010322,PF,S8416492,Y,A13794823,NaN,92282,None,MEDCIN,FN,92282,"meningeal tuberculoma TB (+) culture, (-) micr...",3,N,NaN,None
1,C2104214,ENG,P,L7388914,PF,S8416495,Y,A13990820,NaN,92283,None,MEDCIN,PT,92283,"meningeal tuberculoma TB (+) histology, (-) ba...",3,N,NaN,None
2,C2104214,ENG,S,L7312975,PF,S8416494,Y,A14043755,NaN,92283,None,MEDCIN,FN,92283,"meningeal tuberculoma TB (+) histology, (-) ba...",3,N,NaN,None
3,C2104215,ENG,P,L7086214,PF,S8416497,Y,A13825060,NaN,92284,None,MEDCIN,PT,92284,meningeal tuberculoma TB (+) other way (-) bac...,3,N,NaN,None
4,C2104215,ENG,S,L7539591,PF,S8416496,Y,A13545850,NaN,92284,None,MEDCIN,FN,92284,meningeal tuberculoma TB (+) other way (-) bac...,3,N,NaN,None

In [ ]:
spark.sql("select * from MRCONSO where STR = 'Brain fog'").toPandas()

,CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,SDUI,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF,dummy
0,C0015676,ENG,S,L17155686,VC,S20733128,N,A35442378,NaN,None,10088940,MDR,LLT,10088940,Brain fog,3,N,256,None
1,C0015676,ENG,S,L17155686,VC,S20733128,N,A35442678,NaN,None,10088940,MDR,PT,10088940,Brain fog,3,N,256,None
2,C0015676,ENG,S,L17155686,VC,S20733128,Y,A33194066,NaN,None,HP:0033630,HPO,PT,HP:0033630,Brain fog,0,N,256,None

In [ ]:
mrhier_sdf = load_umls_table("MRHIER", UMLS_DIRECTORY, table_column_dict)
mrhier_sdf, mrhier_path = write_parquet_file_and_reload(spark, mrhier_sdf, "MRHIER", UMLS_OUTPUT_DIRECTORY)

In [ ]:
spark.sql("select * from MRHIER where SAB='HPO'").limit(5).toPandas()

,CUI,AUI,CXN,PAUI,SAB,RELA,PTR,HCD,CVF,dummy
0,C0000727,A33193765,1,A24670862,HPO,isa,A24672666.A24681708.A24674976.A27414154.A27414...,None,None,None
1,C0000727,A33193765,2,A24670862,HPO,isa,A24672666.A24681708.A24674976.A28255478.A24674...,None,None,None
2,C0000729,A30925085,1,A24670862,HPO,isa,A24672666.A24681708.A24674976.A27414154.A27414...,None,None,None
3,C0000729,A30925085,2,A24670862,HPO,isa,A24672666.A24681708.A24674976.A28255478.A24674...,None,None,None
4,C0000731,A24677906,1,A24679016,HPO,isa,A24672666.A24681708.A24674976.A27414154.A27414...,None,None,None

In [ ]:
mrdef_sdf = load_umls_table("MRDEF", UMLS_DIRECTORY, table_column_dict)
mrdef_sdf, mrdef_path = write_parquet_file_and_reload(spark, mrhier_sdf, "MRDEF", UMLS_OUTPUT_DIRECTORY)

In [ ]:
spark.sql("select * from MRDEF").limit(5).toPandas()

,CUI,AUI,ATUI,SATUI,SAB,DEF,SUPPRESS,CVF,dummy
0,C0000039,A0016515,AT38152019,NaN,MSH,Synthetic phospholipid used in liposomes and l...,N,None,None
1,C0000052,A0016535,AT38148809,NaN,MSH,"In glycogen or amylopectin synthesis, the enzy...",N,None,None
2,C0000084,A0016576,AT38151982,NaN,MSH,"Found in various tissues, particularly in four...",N,None,None
3,C0000096,A0526764,AT38133985,NaN,MSH,A potent cyclic nucleotide phosphodiesterase i...,N,None,None
4,C0000097,A0016587,AT38135292,NaN,MSH,A dopaminergic neurotoxic compound which produ...,N,None,None

In [ ]:
mrsab_sdf = load_umls_table("MRSAB", UMLS_DIRECTORY, table_column_dict)
mrsab_sdf, mrsab_path = write_parquet_file_and_reload(spark, mrsab_sdf, "MRSAB", UMLS_OUTPUT_DIRECTORY)

In [ ]:

mrsab_sdf.limit(5).toPandas()

,VCUI,RCUI,VSAB,RSAB,SON,SF,SVER,VSTART,VEND,IMETA,...,CXTY,TTYL,ATNL,LAT,CENC,CURVER,SABIN,SSN,SCIT,dummy
0,C1140144,C1137110,ICD10_1998,ICD10,"ICD10, 1998",ICD10,1998,None,None,2004AB,...,FULL,"HS,HT,HX,PS,PT,PX",None,ENG,UTF-8,Y,Y,International Classification of Diseases and R...,;;;;International Statistical Classification o...,None
1,C1140179,C1140178,ICD10AE_1998,ICD10AE,"ICD10, American English Equivalents, 1998",ICD10,1998,None,None,1998AA,...,None,"HS,HT,HX,PS,PT,PX",None,ENG,UTF-8,Y,Y,"ICD-10, American English Equivalents",;;;;International Statistical Classification o...,None
2,C1140247,C1140246,ICD10AM_2000,ICD10AM,International Statistical Classification of Di...,ICD10AM,2000,None,None,2000AB,...,FULL,"HT,PS,PT,PX","IAA,IAC,IAD,IAH,IAL,IAN,IAR,IAS,IAT,IAY,INC",ENG,UTF-8,Y,Y,"ICD-10, Australian Modification",;;National Centre for Classification in Health...,None
3,C1140249,C1140248,ICD10AMAE_2000,ICD10AMAE,International Statistical Classification of Di...,ICD10AM,2000,None,None,2002AD,...,None,"HT,PS,PT,PX",None,ENG,UTF-8,Y,Y,"ICD-10, Australian Modification, Americanized ...",;;;;International Statistical Classification o...,None
4,C1178804,C0391807,UWDA173,UWDA,"University of Washington Digital Anatomist, 1.7.3",UWDA,1.7.3,None,None,2003AC,...,FULL-MULTIPLE,"PT,SY",UWT,ENG,UTF-8,Y,Y,Digital Anatomist,"Jose Mejino, M.D.;;;;University of Washington ...",None

In [ ]:
mrsat_sdf = load_umls_table("MRSAT", UMLS_DIRECTORY, table_column_dict)
mrsat_sdf, mrsat_path = write_parquet_file_and_reload(spark, mrsab_sdf, "MRSAT", UMLS_OUTPUT_DIRECTORY)

In [ ]:
mrsat_sdf.limit(5).toPandas()

,VCUI,RCUI,VSAB,RSAB,SON,SF,SVER,VSTART,VEND,IMETA,...,CXTY,TTYL,ATNL,LAT,CENC,CURVER,SABIN,SSN,SCIT,dummy
0,C1140144,C1137110,ICD10_1998,ICD10,"ICD10, 1998",ICD10,1998,None,None,2004AB,...,FULL,"HS,HT,HX,PS,PT,PX",None,ENG,UTF-8,Y,Y,International Classification of Diseases and R...,;;;;International Statistical Classification o...,None
1,C1140179,C1140178,ICD10AE_1998,ICD10AE,"ICD10, American English Equivalents, 1998",ICD10,1998,None,None,1998AA,...,None,"HS,HT,HX,PS,PT,PX",None,ENG,UTF-8,Y,Y,"ICD-10, American English Equivalents",;;;;International Statistical Classification o...,None
2,C1140247,C1140246,ICD10AM_2000,ICD10AM,International Statistical Classification of Di...,ICD10AM,2000,None,None,2000AB,...,FULL,"HT,PS,PT,PX","IAA,IAC,IAD,IAH,IAL,IAN,IAR,IAS,IAT,IAY,INC",ENG,UTF-8,Y,Y,"ICD-10, Australian Modification",;;National Centre for Classification in Health...,None
3,C1140249,C1140248,ICD10AMAE_2000,ICD10AMAE,International Statistical Classification of Di...,ICD10AM,2000,None,None,2002AD,...,None,"HT,PS,PT,PX",None,ENG,UTF-8,Y,Y,"ICD-10, Australian Modification, Americanized ...",;;;;International Statistical Classification o...,None
4,C1178804,C0391807,UWDA173,UWDA,"University of Washington Digital Anatomist, 1.7.3",UWDA,1.7.3,None,None,2003AC,...,FULL-MULTIPLE,"PT,SY",UWT,ENG,UTF-8,Y,Y,Digital Anatomist,"Jose Mejino, M.D.;;;;University of Washington ...",None

In [ ]:
mrrel_sdf = load_umls_table("MRREL", UMLS_DIRECTORY, table_column_dict)
mrrel_sdf, mrrel_path = write_parquet_file_and_reload(spark, mrsab_sdf, "MRREL", UMLS_OUTPUT_DIRECTORY)

In [ ]:
import json
umls_table_dict = {"umls": {
    "MRCONSO": mrconso_path,
    "MRHIER": mrhier_path,
    "MRDEF": mrdef_path,
    "MRSAB": mrsab_path,
    "MRSAT": mrsat_path,
    "MRREL": mrrel_path
  }
}

with open(UMLS_OUTPUT_DIRECTORY + "umls_generated_tables.json", "w") as f:
  json.dump(umls_table_dict, f)